name: MinGW
on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.rdoc'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.rdoc'

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

# Notes:
# Actions console encoding causes issues, see test-all & test-spec steps
#
jobs:
  make:
    runs-on: windows-2022
    name: ${{ github.workflow }} (${{ matrix.msystem }})
    env:
      MSYSTEM: ${{ matrix.msystem }}
      MSYS2_ARCH: x86_64
      CHOST: "x86_64-w64-mingw32"
      CFLAGS:   "-march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong"
      CXXFLAGS: "-march=x86-64 -mtune=generic -O3 -pipe"
      CPPFLAGS: "-D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048"
      LDFLAGS:  "-pipe -fstack-protector-strong"
      UPDATE_UNICODE: "UNICODE_FILES=. UNICODE_PROPERTY_FILES=. UNICODE_AUXILIARY_FILES=. UNICODE_EMOJI_FILES=."
      GITPULLOPTIONS: --no-tags origin ${{github.ref}}
    strategy:
      matrix:
        include:
          - msystem: "MINGW64"
            base_ruby: 2.6
            test_task: [ "check" ] # to make job names consistent
          - msystem: "UCRT64"
            base_ruby: head
            test_task: [ "check" ] # to make job names consistent
      fail-fast: false
    if: ${{ !startsWith(github.event.head_commit.message, '[DOC]') && !contains(github.event.pull_request.labels.*.name, 'Documentation') }}
    steps:
      - run: |
          cat <<EOS
          {
            "ci": "GitHub Actions",
            "env": "${{ github.workflow }} / ${{ matrix.test_task }}",
            "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "commit": "${{ github.sha }}",
            "branch": "${{ github.ref }}",
          }
          EOS

defaults:
  run:
    working-directory: build
    shell: sh
